FROM node:8.1.0

MAINTAINER "Mace Fu"

RUN mkdir -p /home/easyRegister

WORKDIR /home/easyRegister

COPY package.json /home/easyRegister

RUN npm install --registry=https://registry.npm.taobao.org

RUN npm install -g gulp && npm install --quiet && npm cache clean
