db:
  tty: true
  image: mongo:3.4.4
  volumes:
  - /home/app/easyregister/db:/data/db
  stdin_open: true
web:
  environment:
   # DB_1_PORT_27017_TCP_ADDR: db
    PORT: '80'
  tty: true
  image: easyregister:5.0
  ports: 
  - 80:80
  - 465:465
  - 3000:3000
  volumes:
    - /home/nfsshare/EasyRegi/upload:/home/EasyRegi/public/upload
    - /home/nfsshare/EasyRegi/logs:/home/EasyRegi/logs
  links:
  - db:db
